#!/usr/bin/env node

const pkg = require("./package.json");
const { generateXlsx } = require("./lib");
const { program } = require("commander");

program
  .name("glog")
  .description("export git log to excel")
  .version(pkg.version, "-v, --version")

  .option("-e, --email <email>", "export excel path")
  .option("-ep, --exportPath <exportPath>", "filter by committer email")
  .option("-d, --overDate <overDate>", "set hour over date")
  .option(
    "-dn, --overDateName <overDateName>",
    "set hour over date name in excel column"
  )
  .action((options) => {
    generateXlsx(options);
  });

program.parse();
